// generated by Fast Light User Interface Designer (fluid) version 1.0305

#include "bug-gui.h"
#include <iostream>
#include "bug.h"
#include <FL/Fl_PNG_Image.H>

Fl_Double_Window *win=(Fl_Double_Window *)0;

Fl_Box *b=(Fl_Box *)0;

static void cb_Move(button* o, void*){
	std::cout<<"Move"<< endl;
}
static void cb_Turn(button* o, void*){
	std::cout<<"Turn"<< endl;
}
static void cb_Path(button* o, void*){
	std::cout<<"Path"<< endl;
}


Fl_Double_Window* make_window() {
  { win = new Fl_Double_Window(500, 500);
    {new Fl_Button(220, 445, 75, 30, "Move");
	o->callback((Fl_Callback*)cb_Move);
	} // Fl_Button* o
    { b = new Fl_Box(50, 25, 400, 400);
//	Fl_PNG_Image* img[0] = new Fl_PNG_Image(""/*ADD PICTUREFILE*/);
//	Fl_PNG_Image* img[0] = new Fl_PNG_Image(""/*ADD PICTUREFILE*/);
//	Fl_PNG_Image* img[0] = new Fl_PNG_Image(""/*ADD PICTUREFILE*/);
//	Fl_PNG_Image* img[0] = new Fl_PNG_Image(""/*ADD PICTUREFILE*/);
    } // Fl_Box* b
    { new Fl_Button(120, 445, 75, 30, "Turn");
	o->callback((Fl_Callback*)cb_Turn);
    } // Fl_Button* o
    { new Fl_Button(25, 445, 70, 30, "Path");
	o->callback((Fl_Callback*)cb_Path);
    } // Fl_Button* o
    win->end();
  } // Fl_Double_Window* win
  return win;
}
