// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef bug_gui_h
#define bug_gui_h
#include <FL/Fl.H>
#include <iostream>
#include "bug.h"
#inlcude <FL/Fl_PNG_Image.H>
Bug bug;
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win;
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>
extern Fl_Box *b;
Fl_Double_Window* make_window();
#endif
